### PR TITLE
chore(deps-dev): add yarn binary in the repo

### PR DESCRIPTION
**Pull request by trivikr**
### Issue
Internal JS-5639

### Description
Uses vendored yarn version, as downloading yarn sometimes throw network errors failing internal builds

### Testing

This check verifies that globally install yarn classic is able to jump to yarn modern.
We'll remove corepack from internal CI in future commit. We'll retain `packageManager` field for reference.

#### Pre-requisites

Fresh installation of Node.js (uses npm), and globally install yarn classic
```console
$ rm -rf ~/.nvm

$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

$ nvm ls
            N/A
...

$ nvm install 20
...
Now using node v20.18.1 (npm v10.8.2)
Creating default alias: default -> 20 (-> v20.18.1)

$ node -v
v20.18.1

$ npm install -g yarn
```

Download `aws-sdk-js-v3` main branch and yarnPath branch with network enabled.
```console
$ git clone https://github.com/trivikr/aws-sdk-js-v3.git --single-branch --depth 1

$ cd aws-sdk-js-v3

$ aws-sdk-js-v3> git fetch origin yarnPath:yarnPath --depth 1
```

Run the following commands with network disabled

#### Before

Throws error since network is not available to download yarn
```console
$ aws-sdk-js-v3> yarn --version
1.22.22
```

In CI, it uses `yarn@4.5.1` as corepack is enabled

#### After

The globally installed yarn classic jumps to locally provided yarn@4.5.1
```console
$ aws-sdk-js-v3> git checkout yarnPath

$ aws-sdk-js-v3> yarn --version
4.5.1
```

If corepack is enabled, it'll just download `yarn@4.5.1` from registry
```console
$ aws-sdk-js-v3> corepack enable

$ aws-sdk-js-v3> yarn --version  
! Corepack is about to download https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n] Y

4.5.1
```

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by trivikr** [comment]
It looks like corepack attempts to download yarn even though it's available in yarnPath

#### Before

yarn is downloaded by corepack when it's first run, if the version is not already available.

On local machine, it's in mise folder

```console
$ aws-sdk-js-v3> git clone https://github.com/trivikr/aws-sdk-js-v3.git --single-branch --depth 1

$ aws-sdk-js-v3> yarn --version
! Corepack is about to download https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n] n
```

#### After

yarn is used from repository, and is not required to be downloaded by corepack.

```console
$ aws-sdk-js-v3> git fetch origin yarnPath:yarnPath --depth 1

$ aws-sdk-js-v3> git checkout yarnPath

$ aws-sdk-js-v3> yarn --version
! Corepack is about to download https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n] n
```

Tested with `corepack@v0.29.4` on `node@v18.20.5`

**Comment by trivikr** [comment]
It attempts to download corepack with network disabled

#### Pre-requisites

Download `aws-sdk-js-v3` main branch and yarnPath branch with network enabled
```console
$ git clone https://github.com/trivikr/aws-sdk-js-v3.git --single-branch --depth 1

$ cd aws-sdk-js-v3

$ aws-sdk-js-v3> git fetch origin yarnPath:yarnPath --depth 1
```

Run the following commands with network disabled

#### Before

Throws error since network is not available to download yarn
```console
$ aws-sdk-js-v3> yarn --version
! Corepack is about to download https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n] Y

/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21609
    throw new Error(
          ^

Error: Error when performing the request to https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21609:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchUrlStream (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21639:20)
    ... 4 lines matching cause stack trace ...
    at async Object.runMain (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:13392:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async fetch (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21603:16)
      at async fetchUrlStream (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21639:20)
      at async download (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21762:18)
      at async installVersion (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21854:55)
      at async Engine.ensurePackageManager (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:22310:32)
      at async Engine.executePackageManagerRequest (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:22410:25)
      at async Object.runMain (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
    [cause]: Error: getaddrinfo ENOTFOUND repo.yarnpkg.com
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'repo.yarnpkg.com'
    }
  }
}

Node.js v20.18.1
```

#### After

Also throws error
```console
$ aws-sdk-js-v3> git checkout yarnPath

$ aws-sdk-js-v3> yarn --version
! Corepack is about to download https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n] Y

/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21609
    throw new Error(
          ^

Error: Error when performing the request to https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21609:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchUrlStream (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21639:20)
    ... 4 lines matching cause stack trace ...
    at async Object.runMain (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:13392:13
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async fetch (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21603:16)
      at async fetchUrlStream (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21639:20)
      at async download (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21762:18)
      at async installVersion (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:21854:55)
      at async Engine.ensurePackageManager (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:22310:32)
      at async Engine.executePackageManagerRequest (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:22410:25)
      at async Object.runMain (/Users/trivikr/.nvm/versions/node/v20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
    [cause]: Error: getaddrinfo ENOTFOUND repo.yarnpkg.com
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'repo.yarnpkg.com'
    }
  }
}

Node.js v20.18.1
```

**Comment by trivikr** [comment]
Created a feature request with corepack at https://github.com/nodejs/corepack/issues/586

**Comment by trivikr** [comment]
Verified that yarn upgrade will happen smoothly

```console
$ yarn set version 4.5.2

$ git status
On branch yarnPath
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    .yarn/releases/yarn-4.5.1.cjs
        modified:   .yarnrc.yml
        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .yarn/releases/yarn-4.5.2.cjs

$ git diff .yarnrc.yml 
diff --git a/.yarnrc.yml b/.yarnrc.yml
index 225c9c14..18919ce0 100644
--- a/.yarnrc.yml
+++ b/.yarnrc.yml
@@ -1,3 +1,3 @@
 nodeLinker: node-modules
 
-yarnPath: .yarn/releases/yarn-4.5.1.cjs
+yarnPath: .yarn/releases/yarn-4.5.2.cjs

$ git diff package.json 
diff --git a/package.json b/package.json
index 43d84e1b..e22b9438 100644
--- a/package.json
+++ b/package.json
@@ -141,5 +141,5 @@
     ],
     "**/*.{ts,js,md,json}": "prettier --write"
   },
-  "packageManager": "yarn@4.5.1"
+  "packageManager": "yarn@4.5.2"
 }
```

**Review by siddsriv — APPROVED** [review]

**Pull request merged**
