### PR TITLE
chore: remove __type and isa from shapes

### PR DESCRIPTION
**Pull request by trivikr**
*Issue #, if available:*

Following PRs should be merged before this PR:
* ~add tests folder in overwritablePathnames https://github.com/aws/aws-sdk-js-v3/pull/1500~
* ~re-add cloudwatch-events models file https://github.com/aws/aws-sdk-js-v3/pull/1501~
* Remove __type and isa function https://github.com/awslabs/smithy-typescript/pull/208

*Description of changes:*
remove __type and isa from shapes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AllanFly120** [comment]
Can we keep the `__type` and `isa()` in exceptions? Without `isa()` the error handling experience would have a regress. For example, users cannot use type predicate when handling errors with special keys in their interface. Previously, users can:

```javascript
import { SpecialException } from "client-foo";
try {
 ...
} catch (e) {
  if (SpecialException.isa(e)) {
   const key =  e.someSpecialKey // someSpecialKey is available in type
  }
}
```

**Comment by trivikr** [comment]
> Can we keep the `__type` and `isa()` in exceptions?

The `__type` is not required in Exceptions, as `name` property is populated with the same value.

Using `instanceof` is a better solution than using `isa()`
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Handling_a_specific_error

**Comment by trivikr** [comment]
> Using `instanceof` is a better solution than using `isa()`

Actually, comparing `err.name` instead of `instanceof` is also acceptable in JavaScript ecosystem as explained in https://javascript.info/custom-errors#extending-error

```console
// ...
// instead of (err instanceof SyntaxError)
} else if (err.name == "SyntaxError") { // (*)
// ...
```

Although `instanceof` is future-proof.

**Comment by AllanFly120** [comment]
Both `instanceof` and `err.name` work in this case. But `instanceof` will have better type support. If we are going with this path, let's add the support sooner than later: Generating all the error shapes in classes(or constructors) instead of structures.

**Comment by trivikr** [comment]
> Generating all the error shapes in classes(or constructors) instead of structures.

Created a feature request for it at https://github.com/aws/aws-sdk-js-v3/issues/1506

**Review by AllanFly120 — APPROVED** [review]

**Pull request merged**
