### PR TITLE
feat: bump version to 3.0.0

### PR DESCRIPTION
**Pull request by AllanZhengYP**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by trivikr — APPROVED** [review]
Go! Go! Go!

**Review by alexforsyth — COMMENTED** [review]
LGTM!

**Comment by arpowers** [comment]
Congrats guys. Long time coming.

**Comment by vvo** [comment]
GG team :)

**Pull request merged**
