### PR TITLE
fix(middleware-sdk-s3): improve error message on stream upload

### PR DESCRIPTION
**Pull request by kuhe**
### Issue
https://github.com/aws/aws-sdk-js-v3/issues/1920
https://github.com/aws/aws-sdk-js-v3/issues/2348

### Description
- add a warning if the Body of a PutObject request might be a Stream of unknown length.

### Testing
Unit tests added. Manual client testing in a linked workspace.

### CODE REVIEW

**Review by AllanZhengYP — COMMENTED** [review]
Can you provide the rationale why we don't fail the request but log a warning message for future reference?

**Review by AllanZhengYP — APPROVED** [review]

**Comment by kuhe** [comment]
from discussion: check for content length _only_ at this middleware stage. Throw error instead of only warning. Should be safe to assume the request will fail if it reaches this step without having determined the content length.

**Review by AllanZhengYP — CHANGES_REQUESTED** [review]
The original server-side error is actually complaining of missing `Content-Length` header. So instead of validating the input type, we should validate the header.

SDK will calculate the content length injected the `Content-Length` header in [content length middleware](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/middleware-content-length/src/index.ts). In this case, the SDK can still populate the content length if the input is stream and from the file system, hense the API request can succeed.

Regarding whether we should log warning or fail-fast, I think we can keep **warning instead of throw**. Because in browser, browser may populate the content-length header on behalf of users in some cases: [Content-Length is a forbidden header by browser](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length). So fail-fast for customer may block some cases where SDK cannot calculate the content length but brower can.

**Review by AllanZhengYP — APPROVED** [review]
Approve again!

**Pull request merged**
