### PR TITLE
fix(package.json): migrate @aws-sdk/types into devDependencies codegen

### PR DESCRIPTION
**Pull request by alexforsyth**
*Issue #, if available:*
Addressing issue here: https://github.com/aws/aws-sdk-js-v3/issues/1649

Smithy typescript changes: https://github.com/awslabs/smithy-typescript/pull/232
Code generation for 
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by trivikr — APPROVED** [review]

**Comment by alexforsyth** [comment]
Attempting to figure out why the build failed. It is working locally

**Comment by alexforsyth** [comment]
Codebuild failed due to: https://github.com/aws/aws-sdk-js-v3/issues/1539

**Comment by alexforsyth** [comment]
Using empty commit to re kick off build. Will merge if everything passes

**Comment by alexforsyth** [comment]
Codebuild passed. Merging. Travis CI is not relevant here

**Pull request merged**
