### PR TITLE
chore(dep): upgrade typescript to 4.2.4

### PR DESCRIPTION
**Pull request by AllanZhengYP**
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AllanZhengYP** [comment]
This build fails with 
> src/sdk-index-link-client.ts:86:7 - error TS2343: This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.
86       ...clients,
         ~~~~~~~~~~
Found 1 error.

This is likely related to the issue that tslib doesn't export `__spreadArray`: https://github.com/microsoft/tslib/issues/149

**Comment by AllanZhengYP** [comment]
Looks like the tslib already exports `spreadArray` in https://github.com/microsoft/tslib/pull/133. I will try again with latest stlib

**Review by trivikr — APPROVED** [review]

**Comment by vvo** [comment]
Hey there, dunno if that's related but lambdas deployed with 3.13.1 are failing on my side with:

```txt
{
  "errorType": "TypeError",
  "errorMessage": "(0 , tslib__WEBPACK_IMPORTED_MODULE_0__.__spreadArray) is not a function",
  "trace": [
    "TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_0__.__spreadArray) is not a function",
    "    at /var/task/webpack:/turnshift/node_modules/@aws-sdk/middleware-stack/dist/es/MiddlewareStack.js:110:58",
    "    at Array.reduce (<anonymous>)",
    "    at getMiddlewareList (/var/task/webpack:/turnshift/node_modules/@aws-sdk/middleware-stack/dist/es/MiddlewareStack.js:108:1)",
    "    at Object.resolve (/var/task/webpack:/turnshift/node_modules/@aws-sdk/middleware-stack/dist/es/MiddlewareStack.js:190:39)",
    "    at ListTopicsCommand.resolveMiddleware (/var/task/webpack:/turnshift/node_modules/@aws-sdk/client-sns/dist/es/commands/ListTopicsCommand.js:42:1)",
    "    at SNS.Client.send (/var/task/webpack:/turnshift/node_modules/@aws-sdk/smithy-client/dist/es/client.js:10:1)",
    "    at SNS.listTopics (/var/task/webpack:/turnshift/node_modules/@aws-sdk/client-sns/dist/es/SNS.js:348:1)",
    "    at publishMessage (/var/task/webpack:/turnshift/lib/publishMessage.js:31:48)",
    "    at /var/task/webpack:/turnshift/jobs/slackSyncAllOrganizations.js:23:28",
    "    at Array.map (<anonymous>)"
  ]
}
```

Searching for "__spreadArray", which is my error, led me to here. Thanks.

**Comment by oscarmorasu** [comment]
This change also broke our builds. We were referencing the sdk version as `"^3.13.0"`. Because this was only a patch bump newer code started picking up 3.13.1, which throws the __spreadArray missing error.

For now we pinned the version to `"3.13.0"`.

I think this should have been a minor version bump, not a patch.

**Comment by nedjs** [comment]
Should also be mentioned that version 2.0.0 of tslib does not contain the __spreadArray function . That function was introduced in 2.1.0

https://github.com/microsoft/tslib/blob/2.1.0/tslib.d.ts

**Comment by vvo** [comment]
@AllanZhengYP Is this solved now? Should aws-sdk specify tslib 2.1.0 instead of 2.0.0? Thanks

**Pull request merged**
