### PR TITLE
fix(client-s3): use LifecycleConfiguration as the root element for BucketLifecycleConfiguration, as per v2 API

### PR DESCRIPTION
**Pull request by turneand**
fix(client-s3): use LifecycleConfiguration as the root element for BucketLifecycleConfiguration, as per v2 API.

### Issue #
Refs: n/a

### Description
What does this implement/fix? Explain your changes.

When using the v3 API code as below against an internal EMC S3 instance, we get presented with the generic error "MalformedXML: This happens when the user sends a malformed xml..."

```js
import { PutBucketLifecycleConfigurationCommand, S3 } from "@aws-sdk/client-s3";

const s3 = new S3({
  credentials: { ... },
  endpoint: "...",
  forcePathStyle: true,
  region: "us-east-1"
});

const run = async() => {
  try {
    await s3.send(new PutBucketLifecycleConfigurationCommand({
      Bucket: "andy-tst1",
      LifecycleConfiguration: {
        Rules: [
          {
            Expiration: {
              Days: 7,
            },
            Filter: {
              Prefix: "",
            },
            Status: "Enabled",
          }
        ]
      }
    }));
  } catch (err) {
    console.log(err);
  }
};
run();
```

However, when running similar code against the v2 API, it works successfully.

```js
import S3 from 'aws-sdk/clients/s3';

const s3 = new S3({
  accessKeyId: "...",
  secretAccessKey: "...",
  endpoint: "...",
  s3ForcePathStyle: true,
});

s3.putBucketLifecycleConfiguration({
  Bucket: "andy-tst1",
  LifecycleConfiguration: {
	Rules: [
	  {
		Expiration: {
		  Days: 7,
		},
		Filter: {
		  Prefix: "",
		},
		Status: "Enabled",
	  }
	]
  }
}, (err, data) => {
  console.log(err, data);
});
```

The reason appears to be that the XML sent is now as follows in v3
```console
<BucketLifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Rule>...
```

But was the below in v2:
```console
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Rule>...
```

Therefore, this change is to change the root XML element to the version present in the V2 api.

### Testing

Modified locally and tested against a local EMC S3 instance

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ryhinchey** [comment]
thanks for making this PR @turneand!  I'd love to see this land :)

**Comment by trivikr** [comment]
This issue is not reproducible to me.

<details>
<summary>Code and output in v2</summary>

```js
const AWS = require("aws-sdk");

(async () => {
  const region = "us-west-2";
  const client = new AWS.S3({ region });

  const Bucket = `test-bucket-${Date.now()}`;
  await client.createBucket({ Bucket }).promise();
  await client.waitFor("bucketExists", { Bucket }).promise();

  await client
    .putBucketLifecycleConfiguration({
      Bucket,
      LifecycleConfiguration: {
        Rules: [
          {
            Expiration: {
              Days: 7,
            },
            Filter: {
              Prefix: "",
            },
            Status: "Enabled",
          },
        ],
      },
    })
    .promise();

  console.log(
    await client.getBucketLifecycleConfiguration({ Bucket }).promise()
  );

  await client.deleteBucket({ Bucket }).promise();
})();

```

```console
{
  Rules: [
    {
      Expiration: [Object],
      ID: 'YzYzMTJmZDgtYWU4YS00MTdlLTgzNDctZTE5OWYxZTM1ZDM2',
      Filter: [Object],
      Status: 'Enabled',
      Transitions: [],
      NoncurrentVersionTransitions: []
    }
  ]
}
```

</details>

<details>
<summary>Code and output in v3</summary>

```js
const { S3, waitForBucketExists } = require("@aws-sdk/client-s3");

(async () => {
  const region = "us-west-2";
  const client = new S3({ region });

  const Bucket = `test-bucket-${Date.now()}`;
  await client.createBucket({ Bucket });
  await waitForBucketExists({ client }, { Bucket });

  await client.putBucketLifecycleConfiguration({
    Bucket,
    LifecycleConfiguration: {
      Rules: [
        {
          Expiration: {
            Days: 7,
          },
          Filter: {
            Prefix: "",
          },
          Status: "Enabled",
        },
      ],
    },
  });
  console.log(await client.getBucketLifecycleConfiguration({ Bucket }));

  await client.deleteBucket({ Bucket });
})();

```

```console
{
  '$metadata': {
    httpStatusCode: 200,
    requestId: undefined,
    extendedRequestId: 'M4rxRQWos0GOY6ng9JVw78MMgmFi5DM8EVUt2ikfDkIP6cSc8t7Q02OHoUzIwBe3cDdn3M8dDl4=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Rules: [
    {
      Expiration: [Object],
      ID: 'ZDVjMmYwZDMtNGExOS00YmViLWJhMzktMjEyZDZlMjNhZDZi',
      Prefix: undefined,
      Filter: [Object],
      Status: 'Enabled',
      Transitions: undefined,
      NoncurrentVersionTransitions: undefined,
      NoncurrentVersionExpiration: undefined,
      AbortIncompleteMultipartUpload: undefined
    }
  ]
}
```

</details>

Tested in Node.js `v14.15.4` with `@aws-sdk/client-s3@3.5.0`

Can you file a [bug report](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=) for discussion if the issue is reproducible from your side?

**Comment by trivikr** [comment]
Closing this PR as:
* The issue is not reproducible in the code sample provided in https://github.com/aws/aws-sdk-js-v3/pull/1999#issuecomment-782207241. The author is requested to create a [bug report](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=) for discussion.
* Even if PR fixes the bug, the code change needs to be done in Code generator and not the output in in clients/client-s3.

**Comment by trivikr** [comment]
For reference, PutBucketLifecycleConfigurationRequest accepts LifecycleConfiguration as per code and documentation:
* Code: https://github.com/aws/aws-sdk-js-v3/blob/2bd8f6a1f25569f2e05c4e947764514a5c8e9d36/clients/client-s3/models/models_0.ts#L9414
* Documentation: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/modules/putbucketlifecycleconfigurationrequest.html

**Pull request closed without merging**
