### PR TITLE
feat(types): add pagination stopOnSameToken option

### PR DESCRIPTION
**Pull request by kuhe**
### Issue
https://github.com/aws/aws-sdk-js-v3/issues/3490

### Description
Add an option to stop paginators on receiving the same token (indicates tail has been reached).

### Testing
tested in the smithy change

### CODE REVIEW

**Comment by AllanZhengYP** [comment]
@kuhe It looks good. Because this change also updates the generated client's code, can you re-generate the clients? Regarding the CodeBuild failure, you need to merge the upstream PR before restart the CodeBuild.

**Comment by kuhe** [comment]
@AllanZhengYP thanks for the doc update. 

I've pushed the client changes. Something I'd like to PR in the future is a `createPaginator` higher order function to reduce the code size spent on these paginators.

**Comment by AllanZhengYP** [comment]
@kuhe I like the idea of more abstractions. Though I have some questions with the function input. Can you follow up on this in a separate issue / internal doc?

**Review by AllanZhengYP — DISMISSED** [review]

**Review by AllanZhengYP — DISMISSED** [review]
Approve it, please regenerate the paginators after today's release before merging it.

**Review by AllanZhengYP — APPROVED** [review]

**Pull request merged**
