### PR TITLE
feat: merge smithy-codegen to master

### PR DESCRIPTION
**Pull request by trivikr**
*Issue #, if available:*
Refs: https://github.com/aws/aws-sdk-js-v3/issues/677

*Description of changes:*
Created this PR by running the following commands in trivikr fork:
```console
$ git checkout -b rebased-smithy-codegen-from-master -t upstream/smithy-codegen
$ git rebase upstream/master
$ git push origin rebased-smithy-codegen-from-master
```

GitHub "rebase and merge" is not successful because of the error explained in https://github.com/trivikr/aws-sdk-js-v3/pull/5#issuecomment-601910967
After this PR is approved, we'll be doing merge using command line as follows:
```console
$ git checkout master
$ git merge rebased-smithy-codegen-from-master
$ git status
On branch master
Your branch is ahead of 'origin/master' by 599 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
$ git push upstream master
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by trivikr** [comment]
Verified that the README for s3-request-presigner is rebased correctly https://github.com/trivikr/aws-sdk-js-v3/tree/rebased-smithy-codegen-from-master/packages/s3-request-presigner

**Comment by trivikr** [comment]
Ran the following commands to find diff between logs:
```console
$ git checkout rebased-smithy-codegen-from-master
$ git log -n 610 > ~/Downloads/rebased-smithy-codegen-from-master.log
$ git checkout upstream/smithy-codegen
$ git log -n 610 > ~/Downloads/smithy-codegen.log 
$ vimdiff ~/Downloads/rebased-smithy-codegen-from-master.log ~/Downloads/smithy-codegen.log
```

GitHub doesn't allow sharing HTML, so changed extension to txt and attached (download and rename to HTML):
[rebase-vs-smithy-codegen-git-log-diff.txt](https://github.com/aws/aws-sdk-js-v3/files/4378095/rebase-vs-smithy-codegen-git-log-diff.txt)

The three rebased commits can be viewed in vimdiff on scrolling to the bottom
Screen Shot 2020-03-24 at 4 18 40 PM

**Comment by trivikr** [comment]
The commits which are missing are merge commits created during release:

Screen Shot 2020-03-24 at 4 19 58 PM

Screen Shot 2020-03-24 at 4 21 03 PM

Screen Shot 2020-03-24 at 4 20 58 PM

**Comment by trivikr** [comment]
Verified that all commits from `smithy-codegen` are in `rebased-smithy-codegen-from-master`:
```
$ git log -n 610 | grep "Merge branch 'smithy-codegen' of github.com:aws/aws-sdk-js-v3"
    Merge branch 'smithy-codegen' of github.com:aws/aws-sdk-js-v3
    Merge branch 'smithy-codegen' of github.com:aws/aws-sdk-js-v3
    Merge branch 'smithy-codegen' of github.com:aws/aws-sdk-js-v3
    Merge branch 'smithy-codegen' of github.com:aws/aws-sdk-js-v3
    Merge branch 'smithy-codegen' of github.com:aws/aws-sdk-js-v3
```

https://github.com/trivikr/aws-sdk-js-v3/tree/rebased-smithy-codegen-from-master
Screen Shot 2020-03-24 at 4 26 11 PM

https://github.com/aws/aws-sdk-js-v3/tree/smithy-codegen
Screen Shot 2020-03-24 at 4 27 05 PM

The 5 missing commits are merge commits, which are removed during rebasing

**Comment by AllanFly120** [comment]
There an option to keep the merge messages: https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---preserve-merges

**Comment by trivikr** [comment]
We're not going ahead with this change as it changes the committer of the commits (although author remains the same)
Screen Shot 2020-03-24 at 4 42 05 PM

We'll:
* create backup of master
* `git reset --hard` the top 3 commits from master
* rebase smithy-codegen
* cherry-pick the top 3 commits from master backup

**Comment by trivikr** [comment]
Superseded by https://github.com/aws/aws-sdk-js-v3/pull/1046

**Pull request closed without merging**
