### PR TITLE
docs: add notes to discourage external usage of dependencies

### PR DESCRIPTION
**Pull request by AllanFly120**
*Description of changes:*

Some packages are not supposed to be consumed outside the SDK. So add notes to emphasize this. They are default values of client's dependencies. They are published because the modular nature of the service clients, but they are not fully tested/validated for any usecase outside the SDK.

/cc @Amplifiyer @seebees 

Name | external public?
-- | --
abort-controller | YES
body-checksum-browser | NO
body-checksum-node | NO
chunked-blob-reader | NO
chunked-blob-reader-native | NO
chunked-stream-reader-node | NO
client-documentation-generator | NO
config-resolver | NO
credential-provider-cognito-identity | YES
credential-provider-env | YES
credential-provider-imds | YES
credential-provider-ini | YES
credential-provider-node | YES
credential-provider-process | YES
eventstream-handler-node | NO
eventstream-marshaller | YES
eventstream-serde-browser | NO
eventstream-serde-config-resolver | NO
eventstream-serde-node | NO
eventstream-serde-universal | NO
fetch-http-handler | YES
hash-blob-browser | NO
hash-node | NO
hash-stream-node | NO
invalid-dependency | NO
is-array-buffer | NO
is-node | NO(to remove)
md5-js | NO
middleware-apply-body-checksum | YES
middleware-bucket-endpoint | YES
middleware-content-length | YES
middleware-eventstream | YES
middleware-expect-continue | YES
middleware-header-default | YES
middleware-host-header | YES
middleware-location-constraint | YES
middleware-retry | YES
middleware-sdk-api-gateway | YES
middleware-sdk-ec2 | YES
middleware-sdk-glacier | YES
middleware-sdk-machinelearning | YES
middleware-sdk-rds | YES
middleware-sdk-route53 | YES
middleware-sdk-s3 | YES
middleware-sdk-s3-control | YES
middleware-sdk-sqs | YES
middleware-sdk-transcribe-streaming | YES
middleware-serde | YES
middleware-signing | YES
middleware-ssec | YES
middleware-stack | YES
middleware-user-agent | YES
node-http-handler | YES
property-provider | NO
protocol-http | YES
querystring-builder | NO
querystring-parser | NO
region-provider | NO
s3-request-presigner | YES
service-error-classification | YES
sha256-tree-hash | NO
shared-ini-file-loader | YES
signature-v4 | YES
smithy-client | NO
types | YES
url-parser-browser | NO
url-parser-node | NO
util-base64-browser | YES
util-base64-node | YES
util-base64-universal | NO(to remove)
util-body-length-browser | NO
util-body-length-node | NO
util-buffer-from | NO
util-create-request | YES
util-format-url | YES
util-hex-encoding | YES
util-locate-window | YES
util-uri-escape | NO
util-user-agent-browser | NO
util-user-agent-node | NO
util-utf8-browser | YES
util-utf8-node | YES
util-utf8-universal | NO(ro remove)
xml-builder | NO

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by trivikr** [comment]
We'll change terminology to what's done by Lerna https://github.com/lerna/lerna/tree/master/utils/create-symlink#usage

**Comment by Amplifiyer** [comment]
We do use certain packages that are now marked internal, such as util-user-agent-browser to append Amplify's user agent for tracking Amplify metrics and other helper methods to keep consistency with aws-sdk such as @aws-sdk/util-format-url, @aws-sdk/eventstream-marshaller and @aws-sdk/util-utf8-node

**Comment by AllanFly120** [comment]
@Amplifiyer 

I can only find `@aws-sdk/util-user-agent-browser` in the dependencies but cannot find where it's imported. Can this be a mistake and Amplify is not actually using the package?

**Comment by Amplifiyer** [comment]
You are right, it’s no longer required since user-agent can now be appended from the client’s constructors.

**Comment by Amplifiyer** [comment]
Looks good to me!

**Pull request merged**
