### PR TITLE
fix(clients): only trim xml tag values which contain newline

### PR DESCRIPTION
**Pull request by trivikr**
### Issue
Internal JS-2756

### Description
Do not trim values while parsing XML

### Testing
Protocol tests

### Additional context
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/2646

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by trivikr** [comment]
Debugged with a specific test case `Ec2InvalidGreetingError:Error:GreetingWithErrors`

```console
Ec2InvalidGreetingError:Error:GreetingWithErrors

    Failed: "Expected a InvalidGreeting to be thrown, got TypeError instead"

      368 |     if (err.name !== "InvalidGreeting") {
      369 |       console.log(err);
    > 370 |       fail(`Expected a InvalidGreeting to be thrown, got ${err.name} instead`);
          |       ^
      371 |       return;
      372 |     }
      373 |     const r: any = err;

      at Env.fail (../../node_modules/jest-jasmine2/build/jasmine/Env.js:722:61)
      at Object.<anonymous>.it (tests/functional/ec2query.spec.ts:370:7)
```

The parsedObj from xmlParse operation:
* When trimming is enabled:
```json
{
  "Response": {
    "Errors": {
      "Error": {
        "Code": "InvalidGreeting",
        "Message": "Hi"
      }
    },
    "RequestId": "foo-id"
  }
}
```
* When trimming is removed:
```json
{
      "Response": {
        "#text": "\n          \n          \n      ",
        "Errors": {
          "#text": "\n              \n          ",
          "Error": {
            "#text": "\n                  \n                  \n              ",
            "Code": "InvalidGreeting",
            "Message": "Hi"
          }
        },
        "RequestId": "foo-id"
      }
    }
```

**Comment by trivikr** [comment]
PR which introduced logic to read contents from `#text` to fix a bug with LocationConstraint https://github.com/aws/aws-sdk-js-v3/pull/993

**Comment by trivikr** [comment]
**Requirement**: Preserve whitespace values only if they are inside a tag, and not if they appear prior to child tag.

For example, the XML value being returned in protocol_test is:
```xml
<?xml version = "1.0" encoding = "UTF-8"?>
  <SimpleScalarPropertiesInputOutput>
      <stringValue>  </stringValue>
  </SimpleScalarPropertiesInputOutput>
```

When trimming is disabled, the parsed output is:
```json
{
  'SimpleScalarPropertiesInputOutput': { '#text': '\n          \n      ', 'stringValue': '  ' }
}
```

When trimming is enabled, the parsed output is:
```json
{ 'SimpleScalarPropertiesInputOutput': { 'stringValue': '' } }
```

The output we want:
```json
{ 'SimpleScalarPropertiesInputOutput': { 'stringValue': '  ' } }
```

**Review by AllanZhengYP — APPROVED** [review]

**Comment by AllanZhengYP** [comment]
This is approved because the condition of triming the value is stricter than before. But we do need to confirm weather this is a valid test case, should remove the value node from wire response?

**Pull request merged**
