### PR TITLE
docs(upgrading): add waiters and credentials upgrading guide

### PR DESCRIPTION
**Pull request by AllanZhengYP**
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2405

### Description
add waiters and credentials(with all the v2 credentials the their equivalents in v3) to upgrading guide

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by alexforsyth** [comment]
Reference from readme and reference in dev guide

**Comment by alexforsyth** [comment]
API reference?

**Comment by AllanZhengYP** [comment]
@alexforsyth This file is already mentioned in the [README](https://github.com/aws/aws-sdk-js-v3#other-changes), hence the API reference. I will add it to dev guide too.

**Review by alexforsyth — APPROVED** [review]
Nice! +1

**Pull request merged**
