### PR TITLE
chore: update prettier printWidth to 120

### PR DESCRIPTION
**Pull request by trivikr**
*Issue #, if available:*
refs: https://github.com/aws/aws-sdk-js-v3/pull/1180#discussion_r425311569

*Description of changes:*
Test PR to see code when printWidth is increased to 120. Personally, I don't like 120 printWidth

To check in your VSCode instance:
* add trivikr fork as remote
```console
git remote add trivikr git@github.com:trivikr/aws-sdk-js-v3.git
```
* switch to prettier-printWidth-120 branch
```console
git checkout trivikr/prettier-printWidth-120
```

**imports which fit in 120 width**
* Before
```ts
import {
  GetAnalyzerCommand,
  GetAnalyzerCommandInput,
  GetAnalyzerCommandOutput
} from "./commands/GetAnalyzerCommand";
```
* After
```ts
import { GetAnalyzerCommand, GetAnalyzerCommandInput, GetAnalyzerCommandOutput } from "./commands/GetAnalyzerCommand";
```

**method params which fit in 120 width**
* Before
```ts
    optionsOrCb?:
      | __HttpHandlerOptions
      | ((err: any, data?: CreateAnalyzerCommandOutput) => void),
```
* After
```ts
    optionsOrCb?: __HttpHandlerOptions | ((err: any, data?: CreateAnalyzerCommandOutput) => void),
```

**code which fits in 120 width**
* Before
```ts
      if (typeof optionsOrCb !== "object")
        throw new Error(`Expect http options but get ${typeof optionsOrCb}`);
```
* After:
```ts
      if (typeof optionsOrCb !== "object") throw new Error(`Expect http options but get ${typeof optionsOrCb}`);
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AllanFly120** [comment]
I need to train my eye again for such wide line. But have much stance on it as long as we stick to it

**Comment by trivikr** [comment]
We decided to go ahead with 120 printWidth in internal discussions.

Screenshots taken on 27-inch 4K monitor, where VSCode occupies 2/3rds of the available horizontal screen space. VSCode setting updated with `"editor.rulers": [80, 100, 120]` for comparison.
 
<details>
<summary>With sidebar (120 ruler not visible)</summary>

27-inch-4K-monitor-two-thirds-screenshot-with-code

</details>

<details>
<summary>Without sidebar (120 ruler visible)</summary>

27-inch-4K-monitor-two-thirds-screenshot-with-code-without-sidebar

</details>

**Comment by alexforsyth** [comment]
Using Dell 27in Ultrasharp 4k, scaled to 1920x1080 equivalent. VSCode takes about 3/4 of the monitor. 

120:


100:



120 looks far better in my opinion.

**Comment by trivikr** [comment]
Follow-up PR posted after removing prettier@1 defaults in https://github.com/aws/aws-sdk-js-v3/pull/1185

**Pull request closed without merging**
